// frontend/vue/App.vue
<template>
  <div style="padding: 20px; font-family: sans-serif;">
    <h1>Vue.js Example</h1>
    <div v-if="loading">
      <p>Loading...</p>
    </div>
    <div v-else-if="data">
      <p>Message: {{ data.message }}</p>
      <p>Timestamp: {{ data.timestamp }}</p>
    </div>
  </div>
</template>

<script>
export default {
  name: 'App',
  data() {
    return {
      data: null,
      loading: false,
    };
  },
  mounted() {
    this.fetchData();
  },
  methods: {
    async fetchData() {
      this.loading = true;
      try {
        const response = await fetch('/api/hello');
        this.data = await response.json();
      } catch (error) {
        console.error('Error:', error);
      } finally {
        this.loading = false;
      }
    },
  },
};
</script>

<style scoped>
</style>

// frontend/react/App.jsx
import React, { useState, useEffect } from 'react';

function App() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      try {
        const response = await fetch('/api/hello');
        const json = await response.json();
        setData(json);
      } catch (error) {
        console.error('Error:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, []);

  return (
    <div style={{ padding: '20px', fontFamily: 'sans-serif' }}>
      <h1>React Example</h1>
      {loading ? (
        <p>Loading...</p>
      ) : (
        data && (
          <div>
            <p>Message: {data.message}</p>
            <p>Timestamp: {data.timestamp}</p>
          </div>
        )
      )}
    </div>
  );
}

export default App;
